### ISSUE TITLE
Gitter + Backlog

### ISSUE THREAD

**Issue by bradder555** [giraffe-fsharp/Giraffe.ViewEngine#4]
If we have a backlog / kanban of some sort myself and others can assist with bug fixes, features, etc...

Would be nice to have a gitter/slack/discord... for contributors to discuss features & decisions.

**Comment by dustinmoris** [comment]
Hi @bradder555!

Agreed! I am kind of waiting for the GitHub Discussions feature to be available to this organisation. I think that would be the ideal place.

Regarding Backlog/Kanban, that's a great idea too, however I want to say that I don't want to act/be seen as the person who decides a "roadmap" and just sticks stuff on a board and then just work on that. That feels wrong to me. I am taking the approach that anyone who has an interest in this or another Giraffe project should raise an issue, discuss the functionality with me and other contributors and then these issues itself become the backlog. If there's a lot of issues being raised then I will help to organise those into individual milestones and group issues together into buckets which probably make sense to release together, otherwise I quite enjoy the very fluid working style of OSS :)

Have you had any other thoughts on this?

**Comment by bradder555** [comment]
TBH, I think open source works best when there is a bit of a leader / vision (like the linux kernel)

So i think one set of hands (yours) steering the ship makes the most sense.

That being said, i don't think decisions should be made in a vacuum, i think the best ideas / decisions / creativity come from the discussions between passionate people.

Having a prioritized backlog would be great, since I haven't been building pages / apis for a bit, so I haven't been thinking of changes or improvements; TBH I thought it was pretty much 'complete' prior to all the new features you've recently added. 

So a backlog would be great, because I wouldn't need to think of any new features, but if I see something on the backlog that interests me, I can assign that to myself and get started on it (the same goes for anyone else).

I would like to avoid the situation where two people work on the same feature / improvement at the same time.

It would be great to try and get some people new to code and contributing working on the viewEngine, because the project is somewhat atomic with very clear scope and goals, i don't think it would be a too odious project for 'new players' to contribute, develop the code and theirselves.

Finally, with concurrent development taking place, it will _force_ all contributors to be disciplined in their commits + PRs, since 3-way merges are a pain in the butt!

**Comment by dustinmoris** [comment]
Hi, Giraffe has now GitHub Discussions enabled and I've created an org wide Kanban board with all repositories linked. Thanks for the feedback!
